Note:

    These numbers indicates the data for each months, 
    Len of list equal to len of months

In [10]:
#Data    
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

* profit for each month
* profit after tax for each month (the tax rate is 30%)
* profit margin for each month - equals to profit after tax divided by revenue
* good months - where the profit after tax was greater than the mean for the year
* bad months - where the profit after tax was less than the mean for the year
* the best month - where the profit after tax was max for the year
* the worst month - where the profit after tax was min for the year
* bonus - add 10% of profit (after tax) mean for  good months
* penalty - subtract 10% of profit (after tax) mean for  good months
* result - show good and bad months's name

----

In [11]:
import numpy as np
revenue = np.array(revenue)
expenses = np.array(expenses)

### 1

In [12]:
profit = revenue - expenses

In [13]:
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

### 2

In [14]:
profit = (profit * 70)/100

In [15]:
profit

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

### 3

In [19]:
profit_margin = profit/revenue * 100

In [20]:
profit_margin

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

---

### 4

In [21]:
profit.mean()

1750.6813333333332

In [24]:
l_m = ['January','February','March','April','May','June','July','August','September','October','November','December']

In [38]:
for i in range(0,len(l_m)):
    if profit[i] > profit.mean():
        print(l_m[i])

January
June
July
August
September
December


---

### 5

In [28]:
for i in range(0,len(l_m)):
    if profit[i] < profit.mean():
        print(l_m[i])

February
March
April
May
October
November


---

### 6

In [35]:
for i in range(0,len(l_m)):
    if profit[i] == profit.max():
        print(l_m[i],'--->',profit[i])

December ---> 8140.678000000001


---

### 7

In [36]:
for i in range(0,len(l_m)):
    if profit[i] == profit.min():
        print(l_m[i],'--->',profit[i])

March ---> -2595.4530000000004


---

### 8

In [41]:
for i in range(0,len(l_m)):
    if profit[i] > profit.mean():
        print( l_m[i],' with bonus --> : ',round(profit[i] + (profit.mean()*10/100) ))

January  with bonus --> :  1941.0
June  with bonus --> :  5261.0
July  with bonus --> :  5922.0
August  with bonus --> :  2937.0
September  with bonus --> :  2505.0
December  with bonus --> :  8316.0


---

### 9

In [42]:
for i in range(0,len(l_m)):
    if profit[i] < profit.mean():
        print( l_m[i],' with penalty --> : ',round(profit[i] - (profit.mean()*10/100) ))

February  with penalty --> :  1163.0
March  with penalty --> :  -2771.0
April  with penalty --> :  -2215.0
May  with penalty --> :  -595.0
October  with penalty --> :  -1742.0
November  with penalty --> :  287.0


---